//
//  def.h
//  This file is generated by stubgen2.
//

//
// Copyright 2002 Sony Corporation 
//
// Permission to use, copy, modify, and redistribute this software for
// non-commercial use is hereby granted.
//
// This software is provided "as is" without warranty of any kind,
// either expressed or implied, including but not limited to the
// implied warranties of fitness for a particular purpose.
//

#ifndef _def_h_DEFINED
#define _def_h_DEFINED

//
//  Object name
//
const char* const objectName = "UDPBeacon";

//
//  Number of OObserver & OSubeject instances
//
const int numOfSubject  = 1;
const int numOfObserver = 3;

//
//  Service name
//
const char* const subjectService[numOfSubject] = 
{
	"UDPBeacon.DummySubject.DoNotConnect.S"
};

const char* const observerService[numOfObserver] = 
{
	"UDPBeacon.Sensor.OSensorFrameVectorData.O",
	"UDPBeacon.ObjInfo.CdtInfo.O",
	"UDPBeacon.STNInfo.STNInfo.O"
};

//
//  OSubject Index
//
const int sbjDummySubject = 0;

//
//  OObserver Index
//
const int obsSensor = 0;
const int obsObjInfo = 1;
const int obsSTNInfo = 2;


#endif // _def_h_DEFINED
