//
//  TinyFTPDStub.h
//  This file is generated by stubgen2.
//

//
// Copyright 2002 Sony Corporation 
//
// Permission to use, copy, modify, and redistribute this software for
// non-commercial use is hereby granted.
//
// This software is provided "as is" without warranty of any kind,
// either expressed or implied, including but not limited to the
// implied warranties of fitness for a particular purpose.
//

#ifndef _stub_h_DEFINED
#define _stub_h_DEFINED

#ifndef OPENR_STUBGEN
#define OPENR_STUBGEN
#endif

#include <OPENR/OPENR.h>
#include <OPENR/OPENRMessages.h>
#include <OPENR/ObjcommMessages.h>
#include <OPENR/stub_macro.h>
#include "def.h"

extern "C" {
    StubFuncDeclare_Basic(Init)
    StubFuncDeclare_Basic(Start)
    StubFuncDeclare_Basic(Stop)
    StubFuncDeclare_Basic(Destroy)
    StubFuncDeclare_Subject(0)
    StubFuncDeclare_Observer(0)
    void _ListenContforPI(void*);
    void _SendContforPI(void*);
    void _ReceiveContforPI(void*);
    void _CloseContforPI(void*);
    void _ListenContforDTP(void*);
    void _ConnectContforDTP(void*);
    void _SendContforDTP(void*);
    void _ReceiveContforDTP(void*);
    void _CloseContforDTP(void*);
}

#endif // _stub_h_DEFINED

